# Generated by Django 2.1.8 on 2019-07-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
