# Generated by Django 2.1.8 on 2019-08-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190801_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
