# Generated by Django 2.1.8 on 2019-08-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_solution_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Solution'),
        ),
    ]
