# Generated by Django 2.1.8 on 2019-08-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_assigned',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
