# Generated by Django 2.1.8 on 2019-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190801_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postiton',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
