# Generated by Django 2.1.8 on 2019-08-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_postiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='postiton',
            new_name='position',
        ),
    ]
