# Generated by Django 2.1.8 on 2019-08-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190801_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='position',
            new_name='postiton',
        ),
    ]
