# Generated by Django 2.1.8 on 2019-08-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_emailconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
